name: Test Master

on:
  workflow_dispatch:

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max-old-space-size=4096'

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: useblacksmith/setup-node@65c6ca86fdeb0ab3d85e78f57e4f6a7e4780b391 # v5
        with:
          node-version: 20.x

      - name: Setup corepack and pnpm
        run: |
          npm i -g corepack@0.31
          corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Find nodes-base JSON
        run: |
          cd packages/nodes-base/dist/
          mkdir n8n-exported-json/
          find . -type f -name "*.json" -exec cp --parents {} n8n-exported-json/ \;

      - name: Archive JSON
        uses: actions/upload-artifact@v4
        with:
          name: n8n-exported-json
          path: |
            n8n-exported-json/
